Changes

diff --git a/.github/workflows/3-test-django-env-vars.yaml b/.github/workflows/3-test-django-env-vars.yaml
--- a/.github/workflows/3-test-django-env-vars.yaml
+++ b/.github/workflows/3-test-django-env-vars.yaml
@@ -9,25 +9,26 @@ jobs:
     env:
       DJANGO_DEBUG: 0
       DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
 
-      - name: Setup Python
-        uses: actions/setup-python@v5
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
         with:
           python-version: '3.12'
-
-      - name: Install Requirements
-        run: |
+      - run: |
           python -m pip install pip --upgrade
           python -m pip install -r requirements.txt
-
-      - name: Print Secret Key (Partial)  # Verify the secret is passed correctly
-        run: |
+      - run: |
           echo "DJANGO_SECRET_KEY is set to ${DJANGO_SECRET_KEY:0:5}******"  # Print first 5 characters
-
-      - name: Django Tests
-        working-directory: ./src
-        run: |
+      - run: |
           python manage.py test
+        working-directory: ./src
+      - name: Cleanup
+        run: |
+          find /tmp -type f -name '*.pyc' -delete
+          rm -rf /tmp/__pycache__
+      - name: Handle Test Failures
+        if: steps.Django\ Tests.outcome != 'success'
+        run: |
+          echo "Tests failed. Check logs for details."
+          exit 1
